language: python
python:
  - "2.7"
env: PYTHONPATH=$PWD:$PYTHONPATH PATH=$PWD/bin:$PATH
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install pep8"
script:
  # syntax checks
  - "python -m py_compile ezmomi/ezmomi.py"
  - "python -m py_compile ezmomi/cli.py"
  - "python -m py_compile ezmomi/params.py"
  # pep8 style check
  - "pep8 ezmomi/"
  - "ezmomi --help"
  - "ezmomi --version"
